
package com.czertainly.ca.connector.ejbca.ws;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HardTokenExistsException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class HardTokenExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HardTokenExistsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HardTokenExistsException_Exception(String message, HardTokenExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HardTokenExistsException_Exception(String message, HardTokenExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.czertainly.ca.connector.ejbca.ws.HardTokenExistsException
     */
    public HardTokenExistsException getFaultInfo() {
        return faultInfo;
    }

}
